# Example Site settings

google_analytics: UA-NNNNNNNN-N
title: "Mikaye Aramyan"
header_pages:
  - index.md
  - about.md
  - projects.md

footer: 'follow us on <a href="https://twitter.com/">twitter</a>'

#style: light # dark (default) or light
#listen_for_clients_preferred_style: true # true or false (default)

plugins:
  - jekyll-seo-tag
